### ISSUE TITLE
command line options

### ISSUE THREAD

**Issue by lcc2207** [Scalr/scalr-ctl#130]
I get the following when trying to run scalr-ctl farms list via the command line

scalr-ctl --key_id xxx --secret_key xxx farms list
Usage: scalr-ctl farms list [OPTIONS]
Error: Missing option "--envId".

scalr-ctl --key_id xxx --secret_key --envId 1 xxx farms list
Error: no such option: --envId

**Comment by lcc2207** [comment]
scalr-ctl --version
scalr-ctl, version 2.1.2

**Comment by shaitanich** [comment]
There are global options and command options. 
Options such as --config, --key_id and --secret_key are global and can be used with any command. 
Option --envId is only used by commands of UserAPI scope and there are many other commands that do not recognize --envId. Thus, --envId is a command option and it goes after COMMAND_NAME, not before:
scalr-ctl --key_id xxx --secret_key yyy farms list --envId zzz
